### PR TITLE
attempt to add back 2.6/3.2/3.3 CI per another repo

### PR DESCRIPTION
**Pull request by insignification**
There's probably a way to run the CI on my own fork, but I'll just give it a try via a PR here. Can never have too many PRs :P

### CODE REVIEW

**Comment by insignification** [comment]
Partial success - 2.6 passed but 3.2/3.3 didn't (environment issues)

For reference, here's where I got the changes from:
https://github.com/noahmorrison/chevron/pull/62

I'm keeping this PR for informatonal purposes only - feel free to close it once you decide whether to add 2.6 or not.

**Comment by snoack** [comment]
That is nifty! I would be more than happy to run the tests again on Python 2.6, 3.2 and 3.3.

For reference, even back then when Travis CI still supported Python 3.2 with the default image, I had to pin older versions of `pytest` and `virtualenv`, see d1e4709. Maybe that does the trick?

Anyway, even if we can't make it work on Python 3.2 and 3.3, I would still accept a merge request that at least works for Python 2.6.

**Comment by insignification** [comment]
Okay, I'll look into it a bit later.

**Comment by snoack** [comment]
There we go: a096f0f

**Pull request closed without merging**
